### PR TITLE
fix: 🐛 bugs chatbubble and datasource viewer

### PR DESCRIPTION
**Pull request by OdapX**
✅ Closes: #279 #280

### CODE REVIEW

**Comment by OdapX** [comment]
I dont think it's a good idea to pass data through the router query, it could potentially become tricky to maintain. 
I think for our a case we need a little store to share data, we can consider zustand for this. (and generalize the approach)

**Comment by gmpetrov** [comment]
> I dont think it's a good idea to pass data through the router query, it could potentially become tricky to maintain. I think for our a case we need a little store to share data, we can consider zustand for this. (and generalize the approach)

- why would you need a state manager in PR? 
- IMO initializing state from router.query is a good pattern, as it enable to set the state when page reloads + router.query is reactive 
- I know that a state manager is tempting, but most of the time it's not needed and it can lead to poorly designed codebases as it becomes the defacto solution for managing states. router.query + useSWR is a powerful combo!

**Comment by gmpetrov** [comment]
@OdapX  Still have the offset page issue 
https://www.loom.com/share/b20f1c9139ef4c53abb464d101865b22?sid=2432f603-3cf9-436e-90c8-f22d5a3a1b1b

File
https://bitcoin.org/bitcoin.pdf

Query
What is an electronic coin?

**Comment by OdapX** [comment]
offset issue:
```javascript
const { jumpToPage } = pageNavigationPluginInstance;

// Jump to the third page
jumpToPage(2);
```
[refrence](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/da204fec47b326bfe88ea2a4451511db1a531fdb/changelogs/v2.4.0.md#L48-L54)

**Pull request merged**
